name: ml-gpu-env
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12.10
  - numpy
  - pandas
  - scikit-learn
  - pytorch=2.6.0
  - torchvision
  - torchaudio
  - pytorch-cuda=12.1
  - xgboost
  - matplotlib
  - seaborn
  - pip
  - pip:
      - optuna
